# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
        pip install -r dev_requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        cd tests
        pytest
    - name: Package
      run: |
        pyinstaller -n peloton-to-garmin-win --console --clean --noconfirm --add-data 'config.ini;.' --add-data 'README.md;.' peloton-to-garmin.py
    - name: Create Archive
      uses: papeloto/action-zip@v1
      with:
       files: \dist\peloton-to-garmin-win\
       dest: \dist\peloton-to-garmin-win.zip
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        message: "Create windows distro"
        add: ${{ github.workspace }}\dist\peloton-to-garmin-win.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Bump version and tag
      id: version_bump
      uses: mathieudutour/github-tag-action@v4.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload the artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}\dist\peloton-to-garmin-win.zip
        asset_name: peloton-to-garmin-windows.zip
        tag: ${{ steps.version_bump.outputs.new_tag }}
        body: ${{ steps.version_bump.outputs.changelog }}
      
        
