# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: TagAndRelease

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Bump version and tag
      id: version_bump
      uses: mathieudutour/github-tag-action@v4.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload the artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}\dist\peloton-to-garmin-win.zip
        asset_name: peloton-to-garmin-windows.zip
        tag: ${{ steps.version_bump.outputs.new_tag }}
        body: ${{ steps.version_bump.outputs.changelog }}
